---

private_vars: "vars/private.yml"

bootstrap_vpn: "files/bootstrapvpn.tar"

packages_to_remove:
  - akonadi
  - akonadi-import-wizard
  - akregator
  - calligra-core
  - camorama # SparkyLinux webcam
  - cdrskin # No CD drive in current laptop.
  - dragon
  - espeak-ng
  - falkon
  - florence # SparkyLinux keyboard
  - fprintd # Fingerprint daemon
  - google-noto-emoji-color-fonts # Don't need these fonts.
  - google-noto-sans-gurmukhi-fonts # Don't need these fonts.
  - google-noto-cjk-fonts-common # Don't need these fonts.
  - google-noto-sans-sinhala-vf-fonts # Don't need these fonts.
  - hexchat # SparkyLinux chat
  - initial-setup
  - java-openjdk-headless # Remove Java 12 rolling release. Use specified JDK versions
  - jemalloc
  - juk
  - k3b
  - kaddressbooklibs
  - kdepim-apps-libs
  - kdepim-runtime
  - kf5-akonadi-mime
  - kf5-akonadi-notes
  - kf5-akonadi-server-mysql
  - kf5-grantleetheme
  - kf5-kalarmcal
  - kf5-kdav
  - kf5-kimap
  - kf5-kitinerary
  - kf5-kldap
  - kf5-kmbox
  - kf5-kontactinterface
  - kf5-kpimtextedit
  - kf5-kpimtextedit
  - kf5-kpkpass
  - kf5-ksmtp
  - kf5-libkdepim
  - kf5-libkleo
  - kf5-mailimporter
  - kf5-pimcommon
  - kf5-pimcommon-akonadi
  - kget
  - kleopatra
  - kmag
  - kmail
  - kmines
  - kmouth
  - kolourpaint
  - korganizer
  - kpat
  - krfb
  - kruler
  - krusader
  - ktnef
  - ktorrent
  - libburn # No CD drive in current laptop.
  - libkmahjongg
  - mariadb
  - mariadb-backup
  - mariadb-common
  - mariadb-cracklib-password-check
  - mariadb-embedded
  - mariadb-errmsg
  - mariadb-gssapi-server
  - mariadb-rocksdb-engine
  - mariadb-server
  - mariadb-server-utils
  - mariadb-tokudb-engine
  - open-vm-tools
  - perl-DBD-MySQL
  - perl-DBI
  - perl-Math-BigInt
  - perl-Math-Complex
  - pidgin # SparkyLinux
  - qlipper # SparkyLinux clipboard
  - qt # QT 4.x libraries
  - qt-common # QT 4.x libraries
  - qt-x11 # QT 4.x libraries
  - qt5-qdbusviewer
  - radiotray # SparkyLinux radio
  - speech-dispatcher
  - uget # SparkyLinux
  - virtualbox-guest-additions
  - vokoscreen # Sparkylinux webcast
  - wodim # No CD drive in current laptop.

base_packages_to_install:
  - ansible
  - curl
  - dropbox
  - emacs
  - firefox
  - git
  - google-chrome-stable
  - highlight
  - htop # Process viewer
  - jq
  - keepassxc
  - pwgen
  - libreoffice-calc
  - libreoffice-kde5
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-writer
  - lynx
  - zsh

standard_packages_to_install:
  - CPUFreqUtility
  - android-tools # ADB Bridge
  - aria2 # Download accelerator
  - backintime-qt # Backup
  - bolt # Connection to Thunderbolt dock
  - cherrytree #
               # This brings in:
               # python2-2.7.16-2.fc30.x86_64
               # python2-cairo-1.18.1-1.fc30.x86_64
               # python2-dbus-1.2.8-5.fc30.x86_64
               # python2-libs-2.7.16-2.fc30.x86_64
               # python2-enchant-2.0.0-7.fc30.noarch
               # python2-appindicator-12.10.0-24.fc30.x86_64
  - cryfs # Encrypted file system for dropbox
  - colordiff
  - comps-extras # Extra images for dnfdragora
  - digikam
  - dolphin
  - emacs-auctex
  - emacs-color-theme
  - emacs-common
  - emacs-goodies
  - emacs-json-mode
  - emacs-json-reformat
  - emacs-json-snatcher
  - emacs-rpm-spec-mode
  - emacs-yaml-mode
  - fuse-exfat # Mounting exfat filesystems
  - google-noto-sans-fonts # Basic Noto fonts.
  - gnome-themes-extra # Installs GTK3 Adwaita[-dark] themes
  - gnupg2
  - gstreamer1-libav # Gstreamer plugin for mpeg4 decoding.
  - gwenview
  - hplip
  - httpie
  - kaccounts-providers # Google authentication
  - kcron
  - kde-connect
  - kdesu
  - kio-gdrive # Google Drive integration
  - kgpg
  - konversation
  - krb5-workstation
  - ksysguard
  - kwalletmanager
  - libva-intel-driver # HW video decode support for Intel integrated graphics
  - libnotify
  - libreoffice-langpack-en
  - okular
  - openldap-clients # ldapsearch
  - openssh-clients
  - openvpn
  - overpass-fonts # RH Fonts
  - overpass-mono-fonts # RH Fonts
  - python3-urlgrabber # Used by mead-load-build-dependencies
  - python3-keyring
  - python3-qt5
  - redshift # Time of day screen temperature
  - sirikali # Replacement for plasma-vault as provides Wallet integration and auto-start
  # - slack # Commenting this out until we actually have a need for it.
  - srcclr
  - subversion
  - texlive-pdfjam # pdfnup etc.
  - thunderbird
  - unifont-fonts # Fonts for zsh prompt
  - vlc
  - wireshark
  - xclip
  - xorg-x11-server-utils
  - yarock

internal_packages_to_install:
  - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
  - redhat-internal-cert-install
  - redhat-lsb-core
  - subscription-manager

development_packages_to_install:
  - brewkoji
  - cmake
  - cpio # RPM
  - dmidecode
  - docker
  - expect # Adds unbuffer command for piping with colours
  - fedpkg # Working with Fedora packages (implicitly pulls in python3-click which is needed by cekit)
  - gcc-c++ # C++ Compiler
  - glide # Go dependency manager
  - golang # Go language
  - golang-bin
  - java-1.8.0-openjdk-devel # Explicitly install Java 8 (later Fedora use Java 10)
  - java-1.8.0-openjdk-src # Explicitly install Java 8 src (later Fedora use Java 10)
  - krdc # Remote desktop
  - libvirt # Virtualisation
  - lm_sensors
  - make
  - mock
  - odcs-client # cekit
  - plasma-sdk # For plasmoidviewer
  - podman
  - poetry # Python3 Dependency Mgmt System
  - pylint # Check python code
# Comment out ready for F31
#  - python2-pytest # Fedpkg building python rpms
#  - python2-pytz # For IP_TOOLING.
  - python3-ansi2html # Convert console output (e.g. build logs) to HTML
  - python3-behave # cekit
  - python3-colorlog # cekit
  - python3-docker # cekit
  - python3-docker-squash # cekit
  - python3-gssapi # linfo
  - python3-jenkins-job-builder
  - python3-jinja2 # cekit
  - python3-ldap # cekit
  - python3-lxml # cekit
  - python3-mock # cekit
  - python3-pykwalify # cekit
  - python3-pytest # cekit
  - python3-pytest-mock # cekit
  - python3-pyyaml # cekit
#  - python3-sphinx # cekit (sphinx) RETIRED BY FEDORA
#  - python-sphinx-autobuild # cekit (sphinx) RETIRED BY FEDORA
  - python3-tox # cekit
  - python3-virtualenv
  - qemu-kvm # Virtualisation
  - rhpkg
  - rubygem-jekyll # jekyll site generator (PME)
  - rubygem-minitest
  - source-to-image # cekit
  - texlive-bibtex
  - texlive-latex
  - virt-install
  - virt-manager # Virtual machine manager (alternative : qt-virt-manager)
