---

packages_to_remove:
  - akonadi
  - akonadi-import-wizard
  - akregator
  - calligra-core
  - dragon
  - falkon
  - initial-setup
  - juk
  - k3b
  - kaddressbooklibs
  - kdepim-apps-libs
  - kdepim-runtime
  - kf5-akonadi-mime
  - kf5-akonadi-notes
  - kf5-grantleetheme
  - kf5-kalarmcal
  - kf5-kdav
  - kf5-kimap
  - kf5-kitinerary
  - kf5-kldap
  - kf5-kmbox
  - kf5-kontactinterface
  - kf5-kpimtextedit
  - kf5-kpimtextedit
  - kf5-kpkpass
  - kf5-ksmtp
  - kf5-libkdepim
  - kf5-libkleo
  - kf5-mailimporter
  - kf5-pimcommon
  - kf5-pimcommon-akonadi
  - kget
  - kleopatra
  - kmag
  - kmail
  - kmines
  - kmouth
  - kolourpaint
  - korganizer
  - kpat
  - krdc
  - krfb
  - kruler
  - krusader
  - ktnef
  - ktorrent
  - libkmahjongg
  - qt5-qdbusviewer

packages_to_install:
  - CPUFreqUtility
  - ansible
  - bolt # For connection to Thunderbolt dock
  - cherrytree
  - colordiff
  - curl
  - digikam
  - dolphin
  - dropbox
  - emacs
  - emacs-auctex
  - emacs-color-theme
  - emacs-common
  - emacs-goodies
  - emacs-yaml-mode
  - firefox
  - git
  - gnupg2
  - google-chrome-stable
  - gwenview
  - highlight
  - hplip
  - jq
  - kde-connect
  - kdesu
  - keepassxc
  - kgpg
  - konversation
  - krb5-workstation
  - ksysguard
  - kwalletmanager
  - libnotify
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-writer
  - lynx
  - okular
  - openssh-clients
  - openvpn
  - pwgen
  - python3-keyring
  - python3-qt5
  - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
  - redhat-internal-cert-install
  - redhat-lsb-core
  - slack
  - srcclr
  - subversion
  - thunderbird
  - vlc
  - wireshark
  - xclip
  - xorg-x11-server-utils
  - yarock
  - zsh
