---

packages_to_remove:
  - akonadi
  - akonadi-import-wizard
  - akregator
  - calligra-core
  - camorama # SparkyLinux webcam
  - cdrskin # No CD drive in current laptop.
  - dragon
  - falkon
  - florence # SparkyLinux keyboard
  - hexchat # SparkyLinux chat
  - initial-setup
  - jemalloc
  - juk
  - k3b
  - kaddressbooklibs
  - kdepim-apps-libs
  - kdepim-runtime
  - kf5-akonadi-mime
  - kf5-akonadi-notes
  - kf5-akonadi-server-mysql
  - kf5-grantleetheme
  - kf5-kalarmcal
  - kf5-kdav
  - kf5-kimap
  - kf5-kitinerary
  - kf5-kldap
  - kf5-kmbox
  - kf5-kontactinterface
  - kf5-kpimtextedit
  - kf5-kpimtextedit
  - kf5-kpkpass
  - kf5-ksmtp
  - kf5-libkdepim
  - kf5-libkleo
  - kf5-mailimporter
  - kf5-pimcommon
  - kf5-pimcommon-akonadi
  - kget
  - kleopatra
  - kmag
  - kmail
  - kmines
  - kmouth
  - kolourpaint
  - korganizer
  - kpat
  - krdc
  - krfb
  - kruler
  - krusader
  - ktnef
  - ktorrent
  - libburn # No CD drive in current laptop.
  - libkmahjongg
  - mariadb
  - mariadb-backup
  - mariadb-common
  - mariadb-cracklib-password-check
  - mariadb-embedded
  - mariadb-errmsg
  - mariadb-gssapi-server
  - mariadb-rocksdb-engine
  - mariadb-server
  - mariadb-server-utils
  - mariadb-tokudb-engine
  - perl-DBD-MySQL
  - perl-DBI
  - perl-Math-BigInt
  - perl-Math-Complex
  - pidgin # SparkyLinux
  - qlipper # SparkyLinux clipboard
  - qt # QT 4.x libraries
  - qt-common # QT 4.x libraries
  - qt-x11 # QT 4.x libraries
  - qt5-qdbusviewer
  - radiotray # SparkyLinux radio
  - speech-dispatcher
  - uget # SparkyLinux
  - vokoscreen # Sparkylinux webcast

base_packages_to_install:
  - ansible
  - curl
  - dropbox
  - emacs
  - firefox
  - git
  - google-chrome-stable
  - highlight
  - htop # Process viewer
  - jq
  - keepassxc
  - pwgen
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-writer
  - lynx
  - zsh

standard_packages_to_install:
  - CPUFreqUtility
  - android-tools # ADB Bridge
  - bolt # Connection to Thunderbolt dock
  - cherrytree
  - colordiff
  - emacs-auctex
  - emacs-color-theme
  - emacs-common
  - emacs-goodies
  - emacs-yaml-mode
  - digikam
  - dolphin
  - gnome-themes-extra # Installs GTK3 Adwaita[-dark] themes
  - gnupg2
  - gwenview
  - hplip
  - httpie
  - kde-connect
  - kdesu
  - kgpg
  - konversation
  - krb5-workstation
  - ksysguard
  - kwalletmanager
  - libnotify
  - libreoffice-langpack-en
  - okular
  - openldap-clients # ldapsearch
  - openssh-clients
  - openvpn
  - python2-brewkoji # Brew and Koji libraries
  - python2-urlgrabber # Used by mead-load-build-dependencies
  - python3-keyring
  - python3-qt5
  - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
  - redhat-internal-cert-install
  - redhat-lsb-core
  - slack
  - srcclr
  - subversion
  - thunderbird
  - vlc
  - wireshark
  - xclip
  - xorg-x11-server-utils
  - yarock

development_packages_to_install:
  #        - kernel-tools
  #        - qt-virt-manager
  - brewkoji
  - cmake
  - code # Visual Studio Code
  - cpio # RPM
  - dmidecode
  - gcc-c++ # C++ Compiler
  - golang # Go language
  - golang-bin
  - java-1.8.0-openjdk-devel # Explicitly install Java 8 (later Fedora use Java 10)
  - libvirt # Virtualisation
  - lm_sensors
  - make
  - mock
  - plasma-sdk # For plasmoidviewer
  - podman
  - python3-jenkins-job-builder
  - qemu-kvm # Virtualisation
  - rhpkg
  - rpmdiff
  - texlive-bibtex
  - texlive-latex
