---

  - name : Repository - RCM
    yum_repository:
      name: rcm-tools-fedora
      description: RCM Tools for Fedora $releasever (RPMs)
      baseurl: http://{{ rcm_repo }}/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-F-$releasever/compose/Everything/$basearch/os/
      gpgcheck: no
      enabled: yes

  - name : Repository - CSB
    yum_repository:
      name: rhel8
      description: RHEL8 CSB packages
      baseurl: http://{{ csb_repo }}/rhel8-csb
      gpgcheck: yes
      enabled: yes
      priority: "2"
      includepkgs: redhat*,slack,bluejeans
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk
