---


# Use this as choco package is out of date
- name: Install Sumatra
  win_package:
    path: https://www.sumatrapdfreader.org/dl2/SumatraPDF-3.2-64-install.exe
    product_id: SumatraPDF
    arguments:
    - /with-filter
    - /with-preview
    - /d 'C:\Program Files (x86)\SumatraPDF'
    - /s
    - /install
    state: present

- name: Install Digikam
  win_package:
    path: http://www.mirrorservice.org/sites/download.kde.org/stable/digikam/7.0.0/digiKam-7.0.0-Win64.exe
    product_id: DigiKam
    arguments:
    - /S
    creates_path: 'C:\Program Files\DigiKam'
    state: present


# Cache/SHA problems (plus out of date) compared to chocolaty
- name: Install MediaMonkey
  win_package:
    path: https://www.mediamonkey.com/MediaMonkey_Setup.exe
    creates_path: 'C:\Program Files (x86)\MediaMonkey'
    product_id: MediaMonkey
    arguments:
    - /SILENT
    state: present

# https://www.copytrans.net/support/how-to-install-ios-drivers-without-itunes-via-command-prompt/
- name: Check if a service is installed
  win_service:
    name: 'Apple Mobile Device Service'
  register: AppleMDS
- name: ITunes Drivers
  block:
  - win_get_url:
      url: "{{ copytransurl }}"
      dest: '{{ script_location }}\CopyTransDriversInstallers.zip'
      force: true
  - win_unzip:
      src: '{{ script_location }}\CopyTransDriversInstallers.zip'
      dest: "{{ script_location }}"
      delete_archive: yes
  - win_command: '"{{ script_location }}\CopyTransDriversInstaller.exe" /install /musicsupport /silent /quit'
  when: AppleMDS.exists != true


# USB Safely Remove
- name: Verify USB Installation
  win_stat:
    path: 'C:\Program Files (x86)\USB Safely Remove\USBSafelyRemove.exe'
  register: usbsafelyremove
- name: USB Safely Remove
  block:
  - win_copy:
      src: files/usbsafelyremove.ini
      dest: '{{ script_location }}\usbsafelyremove.ini'
  - win_copy:
      src: files/usbsafelyremove-private.opt
      decrypt: yes
      dest: '{{ script_location }}\usbsafelyremove.opt'
  - win_package:
      path: "{{ usbsafelyurl }}"
      creates_path: 'C:\Program Files (x86)\USB Safely Remove'
      arguments:
        - /SILENT /LOADINF='{{ script_location }}\usbsafelyremove.ini'
      state: present
  # https://groups.google.com/forum/#!topic/Ansible-project/-Wr2EuHG76M
  - win_command: '"C:\Program Files (x86)\USB Safely Remove\USBSafelyRemove.exe" /loadsettings "{{ script_location }}\usbsafelyremove.opt"'
  when: usbsafelyremove.stat.exists == false

# Macrium Reflect
- name: Verify Reflect Installation
  win_stat:
    path: 'C:\Program Files\Macrium\Reflect\Reflect.exe'
  register: macriumreflect
- name: Macrium Reflect
  block:
    - get_url:
        url: 'https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdDJxTnVNYmpkZVhoc0VQUDJTU2NJMDdWejRINFE_ZT1qRVpwdVI/root/content'
        dest: '/tmp/reflect_home_setup_x64.exe'
      delegate_to: localhost
    - win_copy:
        src: /tmp/reflect_home_setup_x64.exe
        dest: '{{ script_location }}\reflect_home_setup_x64.exe'
        decrypt: yes
    # Doesn't appear to work with win_package so executing the command directly.
    - win_command: '"{{ script_location }}\reflect_home_setup_x64.exe" /passive /l {{ script_location }}\log.txt /norestart LICKEY={{ reflectlicense }}'
  when:
    - do_reflect != False
    - macriumreflect.stat.exists == False


# TODO : Replace with donation version
#- name: Install Freefilesync
#  win_chocolatey:
#    name: "freefilesync"
#    state: latest

# https://winaero.com/blog/uninstall-and-remove-cortana-in-windows-10-version-2004/
- name: Remove Cortana
  win_shell: |
    Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage
