---

  - name: Repository - Google Chrome
    yum_repository:
      name: google-chrome
      description: Google Chrome
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgcheck: yes
      enabled: yes
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub

  - name : Repository - SourceClear
    yum_repository:
      name: sourceclear
      description: SourceClear YUM Repository
      baseurl: https://download.sourceclear.com/redhat/noarch/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://download.sourceclear.com/redhat/SRCCLR-GPG-KEY


  # RPMFusion ships dropbox so this is unnecessary. Further the RPMFusion
  # version is improved as it has minimal dependencies.
  # - name : Repository - Dropbox
  #   yum_repository:
  #     name: dropbox
  #     description: Dropbox YUM Repository
  #     baseurl: http://linux.dropbox.com/fedora/$releasever/
  #     gpgcheck: yes
  #     enabled: yes
  #     gpgkey: http://linux.dropbox.com/fedora/rpm-public-key.asc

  - name : Repository - RCM
    yum_repository:
      name: rcm-tools-fedora
      description: RCM Tools for Fedora $releasever (RPMs)
      baseurl: http://{{ rcm_repo }}/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-F-$releasever/compose/Everything/$basearch/os/
      gpgcheck: no
      enabled: yes

  - name : Repository - CSB
    yum_repository:
      name: rhel7-csb-stage
      description: RHEL7 CSB packages
      baseurl: http://{{ csb_repo }}/rhel7-csb-stage
      gpgcheck: yes
      enabled: yes
      priority: 2
      includepkgs: redhat*,slack,bluejeans
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk

  - name: Install RPMFusion Free
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version}}.noarch.rpm"
      state: present
    when:  '"rpmfusion-free-release" not in ansible_facts.packages'

  - name: Install RPMFusion NonFree
    dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version}}.noarch.rpm"
      state: present
    when:  '"rpmfusion-nonfree-release" not in ansible_facts.packages'

  - name : Repository - Visual Studio Code
    yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      enabled: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
