---

  - block:
    - name: Install GPG Keys
      package:
        name:
          - distribution-gpg-keys
          state: present
    - name: Import Key 1
      ansible.builtin.rpm_key:
        state: present
        key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_facts.distribution_major_version}}"
    - name: Import Key 2
      ansible.builtin.rpm_key:
        state: present
        key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_facts.distribution_major_version}}"
    when: ansible_distribution == "Fedora"

  - name: Repository - Google Chrome
    yum_repository:
      name: google-chrome
      description: Google Chrome
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgcheck: yes
      enabled: yes
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub

  # https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/
  - name: Install RPMFusion Free
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version}}.noarch.rpm"
      state: present
    when:  '"rpmfusion-free-release" not in ansible_facts.packages'

  - name: Install RPMFusion NonFree
    dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version}}.noarch.rpm"
      state: present
    when:  '"rpmfusion-nonfree-release" not in ansible_facts.packages'

  - name : Repository - Visual Studio Code
    yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgcheck: yes
      enabled: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name : InSyncHQ
    yum_repository:
      name: isynchq
      description: InSyncHQ
      baseurl: http://yum.insync.io/fedora/$releasever/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key


  - name: Enable Fedora Copr for LXD
    command: "dnf copr enable -y rnc/cryfs"
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:rnc:cryfs.repo

  - name: Enable Fedora Copr for Birdtray
    command: "dnf copr enable -y rnc/Birdtray"
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:rnc:Birdtray.repo

  - name: Enable Fedora Copr for CherryTree
    command: "dnf copr enable -y bcotton/cherrytree"
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:bcotton:cherrytree.repo

  - name: Enable Fedora Copr for Tekton CLI
    command: "dnf copr enable -y chmouel/tektoncd-cli"
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:chmouel:tektoncd-cli.repo
