---

- name: CreateScriptDir
  win_file:
    path: "{{ script_location }}"
    state: directory

- name: Retrieve my forked setup
  win_get_url:
    url: https://github.com/rnc/Win10-Initial-Setup-Script/archive/PERSONALCONFIG.zip
    dest: "{{ script_location }}/pc.zip"
    force: true

- name: Unpack it
  win_unzip:
    src: "{{ script_location }}/pc.zip"
    dest: "{{ script_location }}"
    delete_archive: yes

- name: Run the powershell
  win_command: >
    powershell.exe
    -NoProfile
    -ExecutionPolicy Bypass
    -File "{{ script_location }}\Win10-Initial-Setup-Script-PERSONALCONFIG\Win10.ps1"
    -include "{{ script_location }}\Win10-Initial-Setup-Script-PERSONALCONFIG\Win10.psm1"
    -preset "{{ script_location }}\Win10-Initial-Setup-Script-PERSONALCONFIG\Default.preset"
