---

- name: run the playbook tasks on the localhost
  hosts: localhost
  vars_files:
    - vars/private.yml
  vars:
    - vpn_bootstrap: false
  vars_prompt:
  - name: "vpn_password"
    prompt: "Enter VPN password"
    private: yes

  tasks:
#  - name: get variables
#    debug: var=hostvars[inventory_hostname]

  - name: Remove software
    dnf:
      name: "{{ packages_to_remove }}"
      state: absent

  # This is prerequisite for ansible to work on the host.
  - name: Install prerequisite software
    dnf:
      name:
        - python3-libselinux
        - python3-pexpect
      state: present

  - name: Gather package facts
    package_facts:
      manager: auto
    no_log: True

  - block:
    - name: Install bootstrap VPN
      unarchive:
        src: files/bootstrapvpn.tar
        dest: /
    - name: Activate network for bootstrap VPN
      command: nmcli connection reload
    - name: Establish temporary vpn filename
      shell: basename $(tar tf files/bootstrapvpn.tar */system-connections/* )
      register: vpn_filename
    - name: Note this action.
      set_fact:
        vpn_bootstrap: True
    when: '"redhat-internal-NetworkManager-openvpn-profiles-non-gnome" not in ansible_facts.packages'

  - block:
    - name: Connect to VPN
      expect:
        command: nmcli -a connection up '{{ vpn_connection }}'
        echo: yes
        responses:
          vpn.secrets.password: "{{ vpn_password }}"
      register: command_result
      # Handle double connection
      failed_when: '"is already active" not in command_result.stdout'
      changed_when: False
    - debug:
        msg="Verifying VPN connection exists...( if not activate vpn connection by running nmcli -a connection up {{ vpn_connection }} )"
    - name: Check bootstrap VPN exists
      command: ip link show tun0 up
      changed_when: False

  - name: Install all package upgrades
    dnf: name=* state=latest

  - name: Add repositories
    include_role:
      name: repositories

  - name: Set hostname
    hostname:
      name: "{{ hostname }}"

  - name: Check GPG Key exists
    stat:
      path: /etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk
    register: stat_gpg_result
    no_log: True

  - name: Download GPG Key
    get_url:
      url: http://{{ csb_repo }}/rhel7-csb-stage/RPM-GPG-KEY-helpdesk
      dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-helpdesk
    when: not stat_gpg_result.stat.exists

  - block:
    - name: Download SpiderOAK
      get_url:
        url: https://spideroak.com/release/spideroak/rpm_x64
        dest: /tmp/spider.rpm
    - name: Install SpiderOAK
      dnf:
        name: /tmp/spider.rpm
        state: present
    when: '"SpiderOak" not in ansible_facts.packages'

  - name: Install required software
    dnf:
      name: "{{ packages_to_install }}"
      state: present

  - name: Install secondary software (development)
    dnf:
      name:
        - cmake
        - code # Visual Studio Code
        - cpio # RPM
        - dmidecode
        - java-1.8.0-openjdk-devel # Explicitly install Java 8 (later Fedora use Java 10)
        - libvirt # Virtualisation
        - lm_sensors
        - make
        - mock
        - podman
        - python3-jenkins-job-builder
        - qemu-kvm # Virtualisation
        - texlive-bibtex
        - texlive-latex
#        - kernel-tools
#        - qt-virt-manager
#        - rpmdiff
#        - brewkoji
#        - rh-osbs
#        - rhpkg
      state: present

  - name: Remove software
    dnf:
      name:
        - java-openjdk-headless # Old Java 10 installation

  - block:
    - name: Clean bootstrap VPN
      file:
        state: absent
        path: "/etc/NetworkManager/system-connections/{{ vpn_filename }}"
    # Network will be reloaded on system reboot anyway
    - name: Reload network
      command: nmcli connection reload
    when: vpn_bootstrap == True

  - name: Patch VPN
    lineinfile:
      path: "{{ item }}"
      insertafter: "tunnel-mtu=1360"
      line: "username={{ vpn_username }}"
    with_fileglob:
      - "/etc/NetworkManager/system-connections/*.ovpn"

  - name: Allow port ranges for KDEConnect
    firewalld:
      immediate: yes
      permanent: true
      state: enabled
      port: '{{ item }}'
    with_items:
      - "1714-1764/udp"
      - "1714-1764/tcp"

  - name: Patch krb5.conf
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf

  - name: Install minishift
    include_role:
      name: minishift

  - name: User account configuration
    include_role:
      name: user
