---

private_vars: "vars/private.yml"

bootstrap_vpn: "files/bootstrapvpn.tar"

packages_to_remove:
  - akonadi
  - akonadi-import-wizard
  - akregator
  - calligra-core
  - calligra-karbon
  - camorama # SparkyLinux webcam
  - cdrskin # No CD drive in current laptop.
  - dragon
  - espeak-ng
  - falkon
  - florence # SparkyLinux keyboard
  - flatpak
  - fprintd # Fingerprint daemon
  - google-noto-emoji-color-fonts # Don't need these fonts.
  - google-noto-sans-gurmukhi-fonts # Don't need these fonts.
  - google-noto-cjk-fonts-common # Don't need these fonts.
  - google-noto-sans-sinhala-vf-fonts # Don't need these fonts.
  - hexchat # SparkyLinux chat
  - initial-setup
  - jemalloc
  - juk
  - k3b
  - kaddressbooklibs
  - kdepim-apps-libs
  - kdepim-runtime
  - kf5-akonadi-mime
  - kf5-akonadi-notes
  - kf5-akonadi-server-mysql
  - kf5-grantleetheme
  - kf5-kalarmcal
  - kf5-kdav
  - kf5-kimap
  - kf5-kitinerary
  - kf5-kldap
  - kf5-kmbox
  - kf5-kontactinterface
  - kf5-kpimtextedit
  - kf5-kpimtextedit
  - kf5-kpkpass
  - kf5-ksmtp
  - kf5-libkdepim
  - kf5-libkleo
  - kf5-mailimporter
  - kf5-pimcommon
  - kf5-pimcommon-akonadi
  - kget
  - kleopatra
  - kmag
  - kmail
  - kmines
  - kmouth
  - kolourpaint
  - korganizer
  - kpat
  - krfb
  - kruler
  - krusader
  - ktnef
  - ktorrent
  - libburn # No CD drive in current laptop.
  - libkmahjongg
  - libkmahjongg-data
  - mariadb
  - mariadb-backup
  - mariadb-common
  - mariadb-cracklib-password-check
  - mariadb-embedded
  - mariadb-errmsg
  - mariadb-gssapi-server
  - mariadb-rocksdb-engine
  - mariadb-server
  - mariadb-server-utils
  - mariadb-tokudb-engine
  - open-vm-tools
  - perl-DBD-MySQL
  - perl-DBI
  - perl-Math-BigInt
  - perl-Math-Complex
  - pidgin
  - python2
  - qlipper # SparkyLinux clipboard
# Required by DigiKam
#  - qt # QT 4.x libraries
#  - qt-common # QT 4.x libraries
#  - qt-x11 # QT 4.x libraries
  - qt5-qdbusviewer
  - radiotray # SparkyLinux radio
  - speech-dispatcher
  - uget # SparkyLinux
  - virtualbox-guest-additions
  - vokoscreen # Sparkylinux webcast
  - wodim # No CD drive in current laptop.

base_packages_to_install:
  - ansible
  - curl
  - emacs
  - firefox
  - git
  - google-chrome-stable
  - highlight
  - htop # Process viewer
  - insync
  - insync-dolphin
  - jq
  - keepassxc
  - pwgen
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-impress
  - libreoffice-writer
  - lynx
  - zsh

standard_packages_to_install:
  - android-tools # ADB Bridge
  - aria2 # Download accelerator
  - backintime-qt # Backup
  - birdtray # Dock for Thunderbird
  - bolt # Connection to thunderbolt dock
  - cherrytree-future
  - cryfs # Encrypted file system for cloud storage
  - colordiff
  - comps-extras # Extra images for dnfdragora
  - digikam
  - dolphin
  - emacs-auctex
  - emacs-color-theme
  - emacs-common
  - emacs-goodies
  - emacs-json-mode
  - emacs-json-reformat
  - emacs-json-snatcher
  - emacs-rpm-spec-mode
  - emacs-yaml-mode
  - fuse-exfat # Mounting exfat filesystems
  - google-noto-sans-fonts # Basic Noto fonts.
  - gnome-themes-extra # Installs GTK3 Adwaita[-dark] themes
  - gnupg2
#  - gsmartcontrol # SMART Disk GUI
  - gstreamer1-libav # Gstreamer plugin for mpeg4 decoding.
  - gv # Emacs printing preview
  - gwenview
  - hplip
  - httpie
  - ImageMagick # Image analysis/conversion tools
  - jpegoptim # Resize JPEG images
  - kaccounts-providers # Google authentication
  - kcron
  - kde-connect
  - kdesu
  - kio-gdrive # Google Drive integration
  - kgpg
  - konversation
  - krb5-workstation
  - ksysguard
  - kwalletmanager
  - libva-intel-driver # HW video decode support for Intel integrated graphics
  - libnotify
  - libreoffice-langpack-en
  - multimarkdown
  - okular
  - openldap-clients # ldapsearch
  - openssh-clients
  - openvpn
  - overpass-fonts # RH Fonts
  - overpass-mono-fonts # RH Fonts
  - python3-urlgrabber # Used by mead-load-build-dependencies
  - python3-keyring
  - python3-qt5
  # - redshift # Time of day screen temperature
  - sirikali # Replacement for plasma-vault as provides Wallet integration and auto-start
  # - slack # Commenting this out until we actually have a need for it.
  - smb4k
  - subversion
  - texlive-pdfjam # pdfnup etc.
  - thunderbird
  - unifont-fonts # Fonts for zsh prompt
  - vlc
  - wireshark
  - xclip

internal_packages_to_install:
  - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
  - redhat-internal-cert-install
  - redhat-lsb-core
  - subscription-manager

development_packages_to_install:
  - buildah
  - brewkoji
  - cabextract # Extract MS CAB files (https://www.cabextract.org.uk)
  - cmake
  - code # Visual Studio Code
  - cpio # RPM
  - dmidecode
  - expect # Adds unbuffer command for piping with colours
  - fedpkg # Working with Fedora packages (implicitly pulls in python3-click which is needed by cekit)
  - fdupes # Find duplicate files
  - gcc-c++ # C++ Compiler
  - genisoimage # Use to create bootable USB images
  - glide # Go dependency manager
  - golang # Go language
  - golang-bin
  - hugo # CEKit Site Generator
  - java-11-openjdk-devel
  - java-11-openjdk-src
  - krdc # Remote desktop
  - krb5-devel # cekit
  - libvirt # Virtualisation
  - lm_sensors
  - make
  - mock
  - odcs-client # cekit
  - pipenv
  - plasma-sdk # For plasmoidviewer
  - podman
  - poetry # Python3 Dependency Mgmt System
  - pylint # Check python code
  - python3-autopep8 # cekit
  - python3-ansi2html # Convert console output (e.g. build logs) to HTML
  - python3-behave # cekit
  - python3-colorlog # cekit
  - python3-docker # cekit
  - python3-docker-squash # cekit
  - python3-gitlab # gitlabber
  - python3-gssapi # linfo
  - python3-jenkins-job-builder
  - python3-jinja2 # cekit
  - python3-kubernetes # cpaas
  - python3-ldap # cekit
  - python3-lxml # cekit
  - python3-mock # cekit
  - python3-openshift # cpaas
  - python3-pykwalify # cekit
  - python3-pytest # cekit
  - python3-pytest-mock # cekit
  - python3-pyyaml # cekit
  - python3-requests-oauthlib # cpaas
  - python3-sphinx # cekit (sphinx)
#  - python-sphinx-autobuild # cekit (sphinx) RETIRED BY FEDORA
  - python3-tomlkit # commitizen
  - python3-tox # cekit
  - python3-virtualenv
  - qemu-kvm # Virtualisation
  - qgit # Visual git viewer
  - rhpkg
  - rubygem-asciidoctor # CEKit
  - rubygem-jekyll # jekyll site generator (PME)
  - rubygem-minitest
  - skopeo
  - source-to-image # cekit
  - sqlitebrowser # Browse and modify SQLLite DB (e.g. for DigiKam)
  - texlive-a4wide # JacORB
  - texlive-ulem # JacORB
  - texlive-bibtex
  - texlive-latex
  - virt-install
  - virt-manager # Virtual machine manager (alternative : qt-virt-manager)
# Removing till we actually need it.
#  - VirtualBox # Virtual machine manager
#  - kmod-VirtualBox
