---

- name: run the playbook tasks on the localhost
  hosts: windows
  vars:
    - do_vault: true
    - script_location: C:\PowerShellScripts

  tasks:
  - include_vars: packages.yml
  - include_vars: services.yml
  - include_vars: "{{ private_vars }}"
    when: do_vault == true
#    no_log: True

  - debug:
      msg: "Running Ansible for Windows"

  # Install other local users. Don't handle Microsoft account users.
  - name: Create local users
    win_user:
      name: '{{ item.name }}'
      password: '{{ item.password }}'
      groups: '{{ item.groups }}'
      groups_action: 'add'
      state: present
    loop: "{{ user_accounts }}"

  - name: Disable and stop services
    win_service:
      # If state is absent it will remove the service but that can be dangerous.
      state: stopped
      start_mode: disabled
      name: "{{ item }}"
      force_dependent_services: "yes"
    ignore_errors: true
    loop: "{{ services_to_disable_and_stop }}"

  - name: Disable services
    win_service:
      start_mode: disabled
      name: "{{ item }}"
      force_dependent_services: "yes"
    ignore_errors: true
    loop: "{{ services_to_disable }}"

  - name: Disable services
    win_service:
      # If state is absent it will remove the service but that can be dangerous.
      state: stopped
      start_mode: disabled
      name: "{{ item }}"
      force_dependent_services: "yes"
    ignore_errors: true
    loop: "{{ services_to_disable }}"

  - name: Install packages
    win_chocolatey:
      name: "{{ standard_packages_to_install }}"
      state: latest

  - name: Install packages
    win_chocolatey:
      name: "{{ extra_packages_to_install }}"
      state: latest

  - name: Run powershell configurations
    include_role:
      name: powershell

  - name: Install self updating packages
    win_chocolatey:
      name: "{{ self_updating_packages_to_install }}"
      state: latest
      pinned: true

  - name: Install all security, critical, and rollup updates without a scheduled task
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: yes
